INSERT INTO channel (channel_id, channel_name, channel_number, pic_name) VALUES (1, 'EPIX', 100, 'epix.png')
INSERT INTO channel (channel_id, channel_name, channel_number, pic_name) VALUES (2, 'EPIX 2', 101, 'epix-2.png')
INSERT INTO channel (channel_id, channel_name, channel_number, pic_name) VALUES (3, 'EPIX HITS', 102, 'epix-hits.png')
INSERT INTO channel (channel_id, channel_name, channel_number, pic_name) VALUES (4, 'EPIX DRIVE-IN', 103, 'epix-drive-in.png')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name) VALUES (1, 'Sahara', 'The first show', 1, 'Sahara.png')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name) VALUES (2, 'Terror Squad', 'The second show for this channel', 1, 'TerrorSquad.png')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name) VALUES (3, 'Six Shooters', 'The first show', 2, 'SixShooters.png')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name) VALUES (4, 'Strategic Air Command', 'An air movie', 3, 'StrategicAirCommand.png')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name) VALUES (5, 'Stargate', 'The 60s show', 4, 'Stargate.png')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name) VALUES (6, 'Star Trek', 'Space movie', 4, 'StarTrek.png')