INSERT INTO channel (channel_id, channel_name, channel_number, pic_name) VALUES (1, 'EPIX', 100, 'epix.png')
INSERT INTO channel (channel_id, channel_name, channel_number, pic_name) VALUES (2, 'EPIX 2', 101, 'epix-2.png')
INSERT INTO channel (channel_id, channel_name, channel_number, pic_name) VALUES (3, 'EPIX HITS', 102, 'epix-hits.png')
INSERT INTO channel (channel_id, channel_name, channel_number, pic_name) VALUES (4, 'EPIX DRIVE-IN', 103, 'epix-drive-in.png')
INSERT INTO channel (channel_id, channel_name, channel_number, pic_name) VALUES (5, 'TWITCH TV', 104, 'twitch-tv.png')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name, video_code) VALUES (1, 'Sahara', 'The first show', 1, 'Sahara.png', 'VvA4Tbjk8tk')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name, video_code) VALUES (2, 'Terror Squad', 'The second show for this channel', 1, 'TerrorSquad.png', 'urBN5hZkTtM')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name, video_code) VALUES (3, 'Six Shooters', 'The first show', 2, 'SixShooters.png', 'K-FpDMOa6a8')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name, video_code) VALUES (4, 'Strategic Air Command', 'An air movie', 3, 'StrategicAirCommand.png', 'WkQr2T83UJc')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name, video_code) VALUES (5, 'Stargate', 'The 60s show', 4, 'Stargate.png', 'kiJtZUPvJxY')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name, video_code) VALUES (6, 'Star Trek', 'Space movie', 4, 'StarTrek.png', '3PM1pvOzn_w')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name, video_code) VALUES (7, 'Ready Player One', 'A game channel', 5, 'ReadyPlayerOne.png', 'cSp1dM2Vj48')
INSERT INTO show (show_id, show_name, show_description, channel_id, pic_name, video_code) VALUES (8, 'Last Chancery', 'A twitch tv show', 5, 'LastChancery.png', 'Sh4xPxlQJ_s')